name: wsl

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  cmd-hello-world:
    runs-on: windows-latest
    steps:
      - run: Invoke-WebRequest -OutFile wine-rootfs.tar.gz -Uri https://github.com/pbo-linaro/github-actions-wsl/releases/download/HEAD/wine-rootfs.tar.gz
      - run: du -h wine-rootfs.tar.gz
      - run: gunzip wine-rootfs.tar.gz
      - run: wsl --import wine C:/wine wine-rootfs.tar.gz --version 1
      - run: cd c:/wine/rootfs/ && dir
      - run: wsl -l -v
      - run: wsl -d wine wine-arm64 cmd.exe /c 'echo hello world'
