name: wsl

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  cmd-hello-world:
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - run: docker images
      - run: docker run -it --rm linaro/wine-arm64 echo hello
