name: wsl

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  cmd-hello-world:
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - run: docker images
      - run: wget https://github.com/pbo-linaro/github-actions-wsl/releases/download/HEAD/wine-rootfs.tar.gz --output wine-rootfs.tar.gz
      - run: mkdir lol && cd lol && tar xzvf wine-rootfs.tar.gz
