name: wsl

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  cmd-hello-world:
    runs-on: windows-latest
    steps:
      #- name: checkout
      #  uses: actions/checkout@v3
      #- uses: Vampire/setup-wsl@v2
      #  with:
      #    wsl-shell-command: bash -c "cd && bash --noprofile --norc -euo pipefail '{0}'"
      #      - run: docker images
        #- run: wsl --install -d Ubuntu
      - run: cd C:/
      - run: curl https://github.com/pbo-linaro/github-actions-wsl/releases/download/HEAD/wine-rootfs.tar.gz --output wine-rootfs.tar.gz
      - run: start /wait "wsl --import wine C:/wine-lol wine-rootfs.tar.gz --version 1"
        #- run: wsl -d debian # start distrib
        #- run: wsl -d wine # start distrib
      - run: cd c:/wine-lol/rootfs/ && dir
      - run: wsl -l -v
        #- run: wsl -d Ubuntu -u root echo lol
        #- run: wsl -d debian echo lol
      - run: wsl -d wine -u root echo lol
